id: P004409
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W14133
  title: དོར་ཞིའི་གསུང་རྩོམ་ཐོར་བུ།
  author: ''
  volumes:
    bfa54d86b84e4f4da4f7df02d97458aa:
      image_group_id: I1KG10364
      title: ''
      volume_number: 1
      total_pages: 354
      base_file: v001.txt
